name: Release

on:
  workflow_dispatch:
    inputs:
      release_all:
        description: 'Release all modules'
        required: false
        default: false
        type: boolean
      nodos_sdk_version:
        description: 'Nodos SDK Version'
        required: false
        default: ''
        type: string
      clean:
        description: 'Clean build'
        required: false
        default: false
        type: boolean

concurrency:
  group: single
  cancel-in-progress: false

jobs:
  call-release-modules:
    name: Release Modules
    uses: nodos-dev/actions/.github/workflows/release-modules.yml@main
    with:
      ref_name: ${{ github.ref_name }}
      release_all: ${{ github.event_name == 'workflow_dispatch' && fromJson(github.event.inputs.release_all) || false }}
      nodos_sdk_version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.nodos_sdk_version || '' }}
      clean: ${{ github.event_name == 'workflow_dispatch' && fromJson(github.event.inputs.clean) || false }}
      build_number: ${{ github.run_number }}
